update PINCache
dangthaison91/RxTextureDataSources pull request #17
Opened 2018-04-04 00:07 UTC by fumito-ito

Older PINCache causes runtime erorr sometimes.
To avoid this problem, set newer version of PINCache.

refs: https://github.com/TextureGroup/Texture/pull/769

2018-04-17 13:28 UTC, dangthaison91 commented
Is there some new feature of new PinCache version you like to use @fumito-ito ? I not specified dependencies version so users can choose the version they want.

2018-04-18 01:50 UTC, fumito-ito commented
@dangthaison91 No. According to TextureGroup/Texture#769, the runtime error `dyld: Symbol not found: _PINDiskCachePrefix` occurs when using Texture with Carthage. I also have experienced it in my project. To resolve this issue, we can use `PINCache 3.0.1-beta.6` or  later, not latest release version `2.6`.

2018-04-24 03:00 UTC, dangthaison91 requested changes

2018-04-24 03:00 UTC, dangthaison91 commented on Cartfile
> +github "pinterest/PINCache" "3.0.1-beta.6"
Can we allow user use version 3.0 or later by using `~> 1.0` or `>= 1.0`

2018-04-24 03:22 UTC, fumito-ito commented on Cartfile
> +github "pinterest/PINCache" "3.0.1-beta.6"
It will be better than mine. I fixed it.

2018-04-24 03:23 UTC, dangthaison91 approved these changes

2018-04-24 03:24 UTC, merged